- R/vars-rename.R
- tests/testthat/test-select-helpers.R
> Fix renaming of files when .strict = FALSE

- R/tidyselect.R
Otherwise we'll have compatibility issues due to API changes
> Only overtake the vars environment utils

- NEWS.md
- R/vars.R
- man/poke_vars.Rd
- tests/testthat/test-vars.R
> Add has_vars()

- NEWS.md
- R/utils-errors.R
- R/vars-rename.R
- R/vars-select.R
- tests/testthat/test-vars-select.R
> Handle character vectors supplied to `-`

- .Rbuildignore
- .github/move.yml
* Add \.github to .Rbuildignore
> Add move-bot config 🤖

- DESCRIPTION
- R/utils-errors.R
- R/vars-select.R
> Replace glue::collapse() with glue::glue_collapse()

- NEWS.md
- R/select-helpers.R
- man/select_helpers.Rd
- tests/testthat/test-select-helpers.R
adds the option to use Perl regular expressions to select variables.
Fixes #71
> Add perl argument to matches()

- .Rbuildignore
- .gitignore
- .travis.yml
- _pkgdown.yml
issue #96
Verify url to github if moving from tidyverse to r-lib.  
Also need to be addressed a valid URL as output.  
On my laptop, this looks like this:
> add pkgdown site

- R/vars-rename.R
This will address #92, but I'm not sure how to add performance regression testing ᕕ( ᐛ )ᕗ
> add data mask to vars_rename_eval

- NEWS.md
- R/select-helpers.R
- R/utils.R
- R/vars-select.R
- tests/testthat/test-select-helpers.R
- tests/testthat/test-vars-select.R
> Support S3 vectors in `vars_select()` and `one_of()`

- NEWS.md
- R/utils.R
- R/vars-select.R
- man/vars_select.Rd
- tests/testthat/test-inds-combine.R
- tests/testthat/test-vars-select.R
> Warn in case of duplicate renaming

- NEWS.md
- R/utils.R
- R/vars-rename.R
- R/vars-select.R
- tests/testthat/outputs/vars-rename-error-rename-to-existing.txt
- tests/testthat/outputs/vars-rename-error-rename-to-same.txt
- tests/testthat/test-vars-rename.R
> Don't return duplicate names after renaming variables

- DESCRIPTION
- R/vars-rename.R
- R/vars-select.R
> Don't create mask if all inputs are constant

- DESCRIPTION
- NEWS.md
- R/select-helpers.R
- R/utils.R
- R/vars-select.R
- man/select_helpers.Rd
- tests/testthat/outputs/vars-select-bool-scalar-ops.txt
- tests/testthat/outputs/vars-select-bool-symbols.txt
- tests/testthat/test-vars-select-eval.R
```r
iris %>%
select(starts_with("Petal") | ends_with("Length")) %>%
head()
#>   Petal.Length Petal.Width Sepal.Length
#> 1          1.4         0.2          5.1
#> 2          1.4         0.2          4.9
#> 3          1.3         0.2          4.7
#> 4          1.5         0.2          4.6
#> 5          1.4         0.2          5.0
#> 6          1.7         0.4          5.4
iris %>%
select(starts_with("Petal") & ends_with("Length")) %>%
head()
#>   Petal.Length
#> 1          1.4
#> 2          1.4
#> 3          1.3
#> 4          1.5
#> 5          1.4
#> 6          1.7
iris %>%
select(!(starts_with("Petal") & ends_with("Length"))) %>%
head()
#>   Sepal.Length Sepal.Width Petal.Width Species
#> 1          5.1         3.5         0.2  setosa
#> 2          4.9         3.0         0.2  setosa …
```
> Interpret boolean operators in selection contexts

- NEWS.md
- R/select-helpers.R
- R/utils.R
- R/vars.R
- tests/testthat/test-select-helpers.R
> Support length > 1 vectors in matchers

- README.md
- _pkgdown.yml
- vignettes/tidyselect.Rmd
> Remove harmful/unneeded pkgdown customisation

- tests/testthat/test-eval-select.R
- tests/testthat/test-vars-pull.R
> Add missing tests

- NEWS.md
- R/vars-pull.R
- man/vars_pull.Rd
- tests/testthat/_snaps/vars-pull.md
- tests/testthat/test-vars-pull.R
Fixes #258
Not sure that I got `error_arg` right
> Pass error_arg and error_call in vars_pull()

- NEWS.md
- R/helpers-vector.R
- tests/testthat/_snaps/helpers-vector.md
- tests/testthat/test-helpers-vector.R
> Better error for any_of()

- R/helpers-misc.R
- tests/testthat/_snaps/helpers-misc.md
- tests/testthat/test-helpers-misc.R
* Check that offset is a scalar
* Use snapshots to test errors
* Add missing periods
Fixes #211
> Improve last_col() input validation

- NEWS.md
- R/eval-walk.R
- tests/testthat/test-eval-select.R
- tests/testthat/test-eval-walk.R
> Always return a named vector from eval_select()

- NEWS.md
- R/helpers-pattern.R
- man/starts_with.Rd
- tests/testthat/test-helpers-pattern.R
> Add suffix argument to num_range()

- NEWS.md
- R/eval-walk.R
- R/helpers-where.R
- tests/testthat/_snaps/eval-select.md
- tests/testthat/_snaps/helpers-where.md
- tests/testthat/test-helpers-where.R
> Improve `where()` errors

- man/language.Rd
- man/rmd/overview.Rmd
> Tweak overview docs

- DESCRIPTION
- NEWS.md
- R/conditions.R
- R/eval-walk.R
- R/helpers-vector.R
- R/vars-pull.R
- tests/testthat/_snaps/eval-select.md
- tests/testthat/_snaps/eval-walk.md
- tests/testthat/_snaps/helpers-vector.md
- tests/testthat/test-helpers-vector.R
> Match all_of() implementation to any_of()

- NEWS.md
- R/vars.R
- man/faq-selection-context.Rd
- tests/testthat/_snaps/vars.md
- tests/testthat/test-vars.R
> Use help hyperlink in peek_vars()

- NEWS.md
- R/helpers-vector.R
- tests/testthat/_snaps/helpers-vector.md
- tests/testthat/test-helpers-vector.R
> Return integer vector from `all_of()`

- NEWS.md
- R/utils.R
- tests/testthat/test-helpers-pattern.R
> Fix `matches()` with named inputs

- NEWS.md
- R/eval-walk.R
- tests/testthat/_snaps/eval-select.md
- tests/testthat/test-eval-select.R
> Fix detection of renaming

- R/helpers-pattern.R
- man/starts_with.Rd
> Clarify selection helpers & regexes

- DESCRIPTION
- NEWS.md
- R/conditions.R
- R/eval-relocate.R
- tests/testthat/_snaps/eval-bool.md
- tests/testthat/_snaps/eval-relocate.md
- tests/testthat/_snaps/eval-rename.md
- tests/testthat/_snaps/lifecycle-deprecated.md
- tests/testthat/_snaps/vars-pull.md
> Revert to CRAN vctrs

- NEWS.md
- R/eval-walk.R
- R/utils.R
- tests/testthat/_snaps/eval-walk.md
- tests/testthat/test-eval-walk.R
- tests/testthat/test-lifecycle-deprecated.R
> Use lifecycle instead of custom message/warnings

- R/eval-walk.R
- revdep/README.md
- revdep/cran.md
- revdep/failures.md
- revdep/problems.md
- tests/testthat/_snaps/lifecycle-deprecated.md
Before:
```r
mtcars |> dplyr::select(new.env())
#> Error in `dplyr::select()`:
#> ! Must subset columns with a valid subscript vector.
#> ✖ Subscript has the wrong type `environment`.
#> ℹ It must be numeric or character.
```
After:
```r
mtcars |> dplyr::select(new.env())
#> Error in `dplyr::select()`:
#> ! Must subset columns with a valid subscript vector.
#> ✖ Subscript `new.env()` has the wrong type `environment`.
#> ℹ It must be numeric or character.
```
> Supply current expression as error arg to vctrs

- DESCRIPTION
- R/helpers-vector.R
- man/all_of.Rd
`all_of()` and `any_of()` have special behaviour when `x` is a named vector. See #333. 
(First commit to a project)
> Add example of named vector x for all_of() and any_of()

- NEWS.md
- R/eval-walk.R
- R/utils.R
- R/vars-pull.R
- tests/testthat/_snaps/eval-walk.md
- tests/testthat/test-eval-walk.R
> Deprecate `.data` in `pull()` too
