DESCRIPTION

This should allow a lot of old users to use this package. This would also help with our tensorflow/reticulate suit of packages that only requires >= 3.0.0.

Lower the requirement of R version

---

R/tidyselect.R

To avoid conflicts between the variables set by dplyr helpers and those set by tidyselect's.

Overwrite dplyr select functions in old versions

---

NEWS.md
R/utils.R
R/vars-select.R
man/vars_select.Rd
tests/testthat/test-select-vars.R

Includes #12 
Symbols and symbol helpers like `:` and `c()` are now evaluated in the data context only. This addresses https://github.com/tidyverse/dplyr/issues/2904

Fix symbol scoping

---

R/vars-select.R

Includes #12 
With this PR the `recipes` package can issue an error on empty selections.

Signal condition on empty selection

---

NEWS.md
R/utils.R
R/vars-select.R
tests/testthat/test-vars-rename.R
tests/testthat/test-vars-select.R

Also fixes a bug with strings when `.strict` is `FALSE`

Handle strings in `:` expressions

---

NEWS.md
R/select-helpers.R
tests/testthat/test-select-helpers.R

* Issue an error when the variable vector is empty.
* Return column positions rather than column names for consistency with other helpers. This also makes it compatible with functions like `seq()`.

Fix issues with last_col()

---

R/select-helpers.R
man/select_helpers.Rd

- "`ends_with()`: ends with a suffix." (not "with a prefix")
- add "." where missing

typos in select helpers

---

.gitignore
R/vars-select.R
R/vars.R
tests/testthat/test-vars-select.R
tests/testthat/test-vars.R

Related to #61. 
This PR is meant as a conversation starter, and is not ready to be merged. 
What I've done is to let NA and "" through in `peek_vars()` but ignore them when feeding the overscope: 
```r
is_helper <- map_lgl(quos, quo_is_helper)
are_name <- are_name(vars)
data <- set_names(as.list(seq_along(vars)), vars)[!are_name]
overscope <- env_bury(overscope_top, !!! data)
```
so this works: 
```r
> vars_select(c("", "a"), a)
a 
"a" 
> vars_select(c(NA, "a"), a)
a 
"a" 
```
But then this one I had to skip: 
```r
test_that("Missing names are ignored", {
skip("let's discuss this")
scoped_vars(c("foo", NA))
expect_identical(peek_vars(), "foo")
scoped_vars(c("bar", ""))
expect_identical(peek_vars(), "bar")
})
```
not sure how much `peek_vars` is an implementation detail, and this is …

handle empty names gracefully

---

NEWS.md
src/combine_variables.cpp
tests/testthat/test-inds-combine.R

``` r
library(tidyselect)
vars_select(letters, 0)
#> named character(0)
vars_select(letters, 0, 1:2)
#>   a   b 
#> "a" "b"
vars_select(letters, 0, -(1:24))
#>   y   z 
#> "y" "z"
```
The idea is to skip all zero vectors, for #82

vars_select() skips all zero vectors. closes #82

---

.travis.yml
DESCRIPTION

This PR fixe failure in Travis CI.
Tidyverse packages are going to support only R 3.2 or greater, and the suggested dplyr package on CRAN is already doing so.
Thus, I bumped minimum R version to 3.2 in DESCRIPTION and .travis.yml.

Bump minimum R version to 3.2

---

DESCRIPTION
R/vars.R
man/poke_vars.Rd
tests/testthat/test-select-helpers.R

This will fix #73 when merged.
I found that the message "No tidyselect variables were registered." came from `peek_vars()`, which triggered this when there were (understandably) no vars registered in the `vars_env`. 
This now throws better errors like so:
``` r
library("tidyselect")
starts_with("z")
#> `starts_with()` must be used within a *selecting* function
peek_vars()
#> No tidyselect variables were registered.
```
<sup>Created on 2019-07-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
Note that I am unsure of where an option to override the error would go: in the `peek_vars()` or in the helpers?

Add better error message for tidyselect helpers

---

DESCRIPTION

This should make it possible for us to link directly to the tidyselect site from other package documentation (e.g. see https://github.com/tidyverse/dplyr/issues/4529).

Add pkgdown site to DESCRIPTION URL

---

R/vars-rename.R
R/vars-select.R
man/vars_select.Rd

vars-rename.R and vars-select.R both describes the `.strict` parameter, and thus the document has description of `.strict` twice.
This PR fixes it.
Note that I did not run `devtools::document` because I use roxygen 6.1.1 whereas the current version of `tiyselect` uses 6.1.0, and also because I got `Error in getDLLRegisteredRoutines.DLLInfo(dll, addNames = FALSE)`
https://github.com/tidyverse/tidyselect/blob/b8c83cc0292e04701bf0a1b892da4bb1aee47ed3/R/vars-rename.R#L3-L4
https://github.com/tidyverse/tidyselect/blob/b8c83cc0292e04701bf0a1b892da4bb1aee47ed3/R/vars-select.R#L32

doc: integrate description of .strict in vars_select and vars_rename

---

DESCRIPTION
NEWS.md
R/select-helpers.R
R/utils.R
R/vars-select.R
man/vars_select.Rd
tests/testthat/helpers-tidyselect.R
tests/testthat/outputs/vars-select-renaming-to-same.txt
tests/testthat/test-inds-combine.R
tests/testthat/test-vars-select.R

Closes #94.
`vars_select()` now ignores duplicate variables that were not selected:
```r
vars <- c("a", "b", "a")
vars_select(vars, -3)
#>   a   b
#> "a" "b"
vars_select(vars, b)
#>   b
#> "b"
```
If selected, the duplicate variables are renamed to their repaired form:
```r
vars_select(vars, a)
#> New names:
#> * a -> a...1
#> * a -> a...2
#> a...1 a...2
#>   "a"   "a"
vars_select(vars, one_of(c("b", "a")))
#> New names:
#> * a -> a...2
#> * a -> a...3
#>     b a...2 a...3
#>   "b"   "a"   "a"
```
This repairing is not very useful yet because `vars_select()` returns a character vector. Ideally it'd return an integer vector of positions so the duplicate variables can be disambiguated. We'll tackle this as part of the UI update in #89.
I don't expect many breakages as duplicate variable …

Support duplicate variables in `vars_select()`

---

NEWS.md
R/vars-select.R
tests/testthat/outputs/vars-select-context-lookup.txt
tests/testthat/test-vars-select-eval.R

First step towards #76. For now this is a simple message:
```r
vars <- letters[1:4]
vars_select(letters, vars)
#> Note: Selecting non-column variables is brittle.
#> ℹ If the data contains `vars` it will be selected instead.
#> ℹ Use `all_of(vars)` to silence this message.
#>   a   b   c   d
#> "a" "b" "c" "d"
```
We can move on to formally deprecating this kind of lookup in the next version.
I would like to refer to `all_of()` in the message, but there will be a transition period where dplyr hasn't exported the new selectors. To work around this, the second commit binds the selection helpers inside the context mask. This is what several client packages are already doing. This makes it easier to use dplyr functions without the package attached:
```r
dplyr::select(mtcars, …
```

Recommend using `all_of()` for looking up variables

---

NEWS.md
R/select-helpers.R
R/utils.R
R/vars-select-eval.R
R/vars-select.R
man/select_helpers.Rd
tests/testthat/test-select-helpers.R
tests/testthat/test-vars-select-eval.R

* The `.strict` argument is now handled from the selection interpreter, fixing many bugs.
* It is now easier for selection helpers to depend on `.strict`: just return out-of-bounds names or indices, and the interpreter will drop them if `.strict` is FALSE, or throw an OOB error otherwise.
* `all_of()` becomes the identity function. `any_of()` uses the same routine as the interpreter to force non-strict selection.

Add non-strict handling to selection interpreter

---

R/select-helpers.R
R/select.R
R/vars-select-eval.R
R/vars-select.R
tests/testthat/outputs/select-eval-boolean-errors.txt
tests/testthat/outputs/vars-select-bool-symbols.txt
tests/testthat/outputs/vars-select-context-lookup.txt
tests/testthat/test-select-helpers.R
tests/testthat/test-select.R
tests/testthat/test-vars-select-eval.R

Part of #89 and closes #86.
* Takes a vector or data frame and returns a vector of selected positions. Because it takes the whole data as input, it supports predicate selections. Because it returns a vector of positions rather than names, it has better support for duplicated names.
* Unexported `vec_select()` serves as an implementation example. While `vec_select()` has vctrs semantics (but refuses to work with data frames), `select_pos()` has `[` semantics and works with data frames. This should make it easier for packages like tidyr to interface with it.
* Selections are taken via `...` for now, because `c(...)` isn't consistent with `...` yet.
* Will be documented and exported later on when `c(...)` has been fixed. We will switch to a single named parameter to encourage tidyr-like …

Implement `select_pos()`

---

R/conditions.R
R/vars-rename.R
tests/testthat/outputs/eval-errors.txt
tests/testthat/outputs/rename-strict-errors.txt
tests/testthat/test-eval.R

This prevents the function calls from leaking into base errors during evaluation.
Before:
```r
#> Error in eval_tidy(quo, mask): object 'e' not found
```
After:
```r
#> Error: object 'e' not found
```
We should probably use this approach in all data masking APIs, such as in dplyr. cc @batpigandme and @romainfrancois

Sanitise base errors

---

DESCRIPTION

Fixes installation error
```r
remotes::install_github("r-lib/tidyselect")
#> Downloading GitHub repo r-lib/tidyselect@master
#> Error: Failed to install 'tidyselect' from GitHub:
#>   Missing commas separating Remotes: 'r-lib/vctrs
#>     r-lib/rlang'
```

Add missing comma to remotes

---

R/eval-walk.R

Closes #254
```r
Warning messages:
`scoped_bindings()` is deprecated as of rlang 0.4.2.
Please use `local_bindings()` instead.
```

Use `local_bindings()` instead of `scoped_bindings()`

---

NEWS.md
R/eval-walk.R
tests/testthat/test-eval-walk.R

closes #221 
Thanks to @DavisVaughan for suggestion to use `is_empty`

Empty selections don't error with `allow_rename = FALSE`

---

NEWS.md
R/eval-select.R
R/eval-walk.R
R/utils.R
man/eval_select.Rd
tests/testthat/_snaps/eval-select.md
tests/testthat/_snaps/eval-walk.md
tests/testthat/test-eval-select.R
tests/testthat/test-eval-walk.R

Fixes #252
Do you think I need to add an `error_arg` to these errors?

Implement allow_empty

---

vignettes/syntax.Rmd

Fixes #203
I removed most of the discussion about `-`. I don't think it's worth precisely defining the semantics of a syntax that we no longer recommend.

Focus on Boolean algebra

---

man/faq-selection-context.Rd
man/faq/selection-context.Rmd

Fixes #270
After writing this, I'm not sure this is quite the right place, but we definitely need this advice somewhere.

Give advice on reusable selection helpers

---

tests/testthat/_snaps/eval-rename.md
tests/testthat/test-eval-rename.R
tests/testthat/test-eval-select.R

This closes #204 and #215, confirming that they were fixed incidentally in be45ce0ba650e94d37b681537e55df652421fa0f.

Test renaming predicates

---

R/eval-relocate.R
R/eval-walk.R
tests/testthat/_snaps/eval-relocate.md
tests/testthat/_snaps/eval-select.md
tests/testthat/test-eval-relocate.R
tests/testthat/test-eval-select.R

Closes #298 
I didn't add a class to the rethrown error. It seems like the class is just meant for internal use, and I don't see us needing to ever rethrow the already rethrown error, so I didn't think it needed a class.

Add a class to the rename error and rethrow it in `eval_relocate()`

---

R/conditions.R
R/utils.R
tests/testthat/_snaps/eval-select.md

@lionel- I figured you might want to take a quick look because you had some tests that captured the backtrace and this slightly changes the frame numbers (which I think is expected)

Use `try_fetch()` in place of `tryCatch()`

---

DESCRIPTION
NEWS.md
R/conditions.R
R/eval-relocate.R
tests/testthat/_snaps/eval-bool.md
tests/testthat/_snaps/eval-relocate.md
tests/testthat/_snaps/lifecycle-deprecated.md
tests/testthat/_snaps/vars-pull.md
tests/testthat/test-eval-relocate.R

Closes #271 
Requires https://github.com/r-lib/vctrs/pull/1619 (I'll merge that first and then update here)
Note that this means tidyselect now relies on dev vctrs.

Use the new `"select"` and `"relocate"` subscript actions

---

R/helpers-vector.R
tests/testthat/_snaps/helpers-vector.md

I am prepping some of my packages for the updates in tidyselect v1.2.0, and noticed the deprecation message was missing a space between the text and the link to the `?tidyselect::faq-selection-context` document. 🍁 
```
Warning message:
Using `all_of()` outside of a selecting function was deprecated in <NA> 1.2.0.
See details at?tidyselect::faq-selection-context
```

Update deprecation message

---

R/sets.R
R/utils.R

A `profvis()` of this common `c()` case of `eval_select()` shows that one of the biggest performance hits comes from `names_propagate()` inside of the `sel_*()` set ops.
It looks like even an expression like `c(mpg, cyl)` ends up going through the names propagation path, which doesn't seem right (there aren't names to propagate here).
This ends up happening because the `eval_c()` "reduce" path starts with a base `named(int())` value and then unions that with the result of each node, like `mpg` and `cyl`. But the fact that `named(int())` is named at all causes the name propagation path to fire.
I've tweaked this so that deciding whether or not to try names propagation works off `any_valid_names()`, which only returns `TRUE` if:
- Names are not `NULL`
- At least one name is not `""` or `NA` …

Attempt names propagation only when necessary in set ops

---

R/eval-walk.R

Another minor performance improvement, this one related to `eval_sym()`, which should affect most tidyselect calls.
This is actually related to https://github.com/r-lib/rlang/issues/1582, where not supplying a `default` ends up being super slow. We could wait for that fix, but specifying the `default` in the meantime like this would also help
```r
library(tidyselect)
library(rlang)
expr <- expr(c(mpg, cyl))
bench::mark(eval_select(expr, mtcars), iterations = 50000)
#> # A tibble: 1 × 6
#>   expression                     min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 eval_select(expr, mtcars)      1ms   1.28ms      769.    5.37MB     11.3
#> # A tibble: 1 × 6
#>   expression                     min   median …
```

Specify `default` to speed up symbol lookup

---

DESCRIPTION
R/eval-walk.R
R/sets.R

Not sure that this one really has that much performance impact in the most common cases, but I do think it probably starts to help more once you have more complex expressions with multiple calls to `set_*()`
```r
library(tidyselect)
library(rlang)
expr <- expr(c(mpg, cyl))
bench::mark(eval_select(expr, mtcars), iterations = 50000)
#> # A tibble: 1 × 6
#>   expression                     min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 eval_select(expr, mtcars)      1ms   1.27ms      774.    5.37MB     11.5
#> # A tibble: 1 × 6
#>   expression                     min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 eval_select(expr, mtcars) …
```

Replace homegrown set operations with vctrs versions

---

R/conditions.R
R/eval-relocate.R
tests/testthat/_snaps/eval-select.md
tests/testthat/_snaps/vars-pull.md

Probably my last tidyselect micro-optimization
Motivation is that `try_fetch()` is slower than `withCallingHandlers()` and we aren't using any special `try_fetch()` behavior here:
``` r
bench::mark(
rlang = try_fetch(1, error = function(cnd) stop("oh no")),
base = withCallingHandlers(1, error = function(cnd) stop("oh no"))
)
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 rlang       14.01µs  15.97µs    60353.        0B     18.1
#> 2 base         1.93µs   2.59µs   382351.        0B     38.2
```
It does change the backtrace _numbers_ a little but that seems ok?
I know `with_subscript_errors()` is always called at least 1 time per `eval_select()` call, and `with_chained_errors()` is …

Use `withCallingHandlers()` over `try_fetch()` for performance

---

R/eval-walk.R
tests/testthat/_snaps/eval-walk.md

When a predicate function is used in `select()` to select columns for which a function returns `TRUE`, a warning appears, saying: "Please use wrap predicates in `where()` instead.", which is grammatically incorrect.
To correct the warning's grammar, this commit changes the warning to say: "Please use `where()` to wrap predicate functions instead."

Fix grammar in warning about bare predicates

---

DESCRIPTION
tests/testthat/_snaps/eval-relocate.md
tests/testthat/_snaps/eval-select.md
tests/testthat/_snaps/eval-walk.md
tests/testthat/_snaps/helpers-vector.md
tests/testthat/_snaps/helpers.md
tests/testthat/_snaps/vars-pull.md
tests/testthat/test-eval-relocate.R
tests/testthat/test-eval-select.R
tests/testthat/test-eval-walk.R
tests/testthat/test-helpers-vector.R
tests/testthat/test-helpers.R
tests/testthat/test-vars-pull.R

I guess the goal was to have the class of the error.
This PR uses the `cnd_class` argument from `expect_snapshot()` instead.
I decided to use 
```r
expect_snapshot(error = TRUE, cnd_class = TRUE, {
code
})
```
to avoid having a large diff if it is decided the condition class is no longer important in certain tests.

Avoid nested `expect_error()` in snapshot tests

---

NEWS.md
R/helpers-pattern.R
man/starts_with.Rd

Use `perl = TRUE` by default

---

NEWS.md
R/eval-relocate.R
tests/testthat/_snaps/eval-relocate.md

Also remove duplicate news items (it is already on line 15)
Noted that `with_rename_error()` is no longer needed as using `eval_select()` with `error_arg` does the job (better?)

fixup error msg
